// Generates apps/desktop-ui/registered-messages.js: the exact Korean texts the server/collector code can send
// (plain string literals, no interpolation). The UI shows server text only when it is in this registry (allow-list).
// Usage: node tests/ui/tools/gen_registered_messages.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '../../..');
const out = path.join(root, 'apps/desktop-ui/registered-messages.js');
const SOURCES = [['src', /\.cs$/], ['tools/data-pipeline', /\.py$/]];
// The desktop host (WPF shell) never sends text through the API; skip it.
const SKIP_DIRS = new Set(['obj', 'bin', 'node_modules', '__pycache__', 'Nikke.Desktop', 'tests']);
// Literals that name internal identifiers (paths, camelCase, snake_case, dotted names) are not registered.
const INTERNAL = /\w+\.[A-Za-z_]\w*|[a-z]+[A-Z]\w*|[A-Za-z]+_[A-Za-z0-9_]+|[\[\]"]|[\/]\w+[\/]/;

function* walk(dir, test) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full, test);
    else if (test.test(entry.name)) yield full;
  }
}

const found = new Set(); const rejected = new Set();
for (const [dir, test] of SOURCES) {
  for (const file of walk(path.join(root, dir), test)) {
    const text = fs.readFileSync(file, 'utf8');
    for (const m of text.matchAll(/(?<![$@\w])"((?:[^"\\n]|\.)*)"|(?<![\w])'((?:[^'\\n]|\.)*)'/g)) {
      const raw = (m[1] ?? m[2] ?? '').replace(/\\"/g, '"').replace(/\'/g, "'");
      if (!/[가-힣]/.test(raw) || /[{}%]/.test(raw) || raw.length > 200) continue;
      (INTERNAL.test(raw) ? rejected : found).add(raw);
    }
  }
}
const list = [...found].sort();
const body = `/**
 * GENERATED by tests/ui/tools/gen_registered_messages.mjs - do not edit by hand.
 * Exact Korean texts the server/collector code can send. Server text outside this list is never shown.
 */
export const REGISTERED_MESSAGES = new Set(${JSON.stringify(list, null, 1)});
`;
if (process.argv.includes('--check')) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (current.replace(/\r\n/g, '\n') !== body) { console.error('registered-messages.js is out of date'); process.exit(1); }
  console.log(`registered-messages.js up to date (${list.length} texts, ${rejected.size} internal-looking literals excluded)`);
} else {
  fs.writeFileSync(out, body, 'utf8');
  console.log(`wrote ${list.length} texts (${rejected.size} internal-looking literals excluded)`);
}
