// client_f32 UI stage A checks (no browser, no network). Evidence type: MOCK ONLY.
// fixtures/client-f32-mock.json is generated by make_client_f32_mock.py (Python binary32, engine 5ced15a order);
// it is not engine output, not an API response and not a game observation. Passing here is not an
// end-to-end API acceptance.
// Usage: node tests/ui/client_f32_mock.test.mjs
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const root = path.resolve(import.meta.dirname, '../..');
const load = file => import(pathToFileURL(path.join(root, 'apps/desktop-ui', file)));
const policy = await load('hit-policy.js');
const adapter = await load('damage-log-adapter.js');
const viewer = await load('damage-log.js');
const mock = JSON.parse(fs.readFileSync(path.join(import.meta.dirname, 'fixtures/client-f32-mock.json'), 'utf8'));

const checks = [];
async function check(name, fn) {
  try { await fn(); checks.push({ name, passed: true }); }
  catch (error) { checks.push({ name, passed: false, error: String(error.message).split('\n').slice(0, 6).join(' | ') }); }
}
const entryFor = (name, which = 'client_f32', patch = {}) => {
  const c = mock.cases[name];
  const calculation = c.comparison.candidates.find(x => x.policy === which);
  return { hitId: 1, frame: 600, damage: calculation.damage, hit: c.hit, calculation, buffs: [], ...patch };
};
const panel = entry => viewer.renderDamageAuditPanel({ hitId: 1, shotId: 2, seconds: 10 }, adapter.buildHitAudit(entry, null));
const text = html => html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ');

await check('fixture_is_labelled_mock', () => {
  assert.equal(mock.kind, 'ui_mock_not_engine_output');
  assert.equal(mock.wireStatus, 'provisional_until_backend_contract');
});

await check('candidates_client_first_legacy_kept_as_comparison', () => {
  const raw = mock.cases.crit_core_fullburst_distance.comparison.candidates;
  assert.deepEqual(raw.map(c => c.policy), ['legacy_term_floor', 'final_round_even', 'nested_floor', 'client_f32']);
  const { candidates, missing } = policy.orderCandidates(raw);
  assert.deepEqual(candidates.map(c => c.policy), ['client_f32', 'legacy_term_floor', 'final_round_even', 'nested_floor']);
  assert.deepEqual(candidates.map(c => c.info.role), ['default', 'comparison', 'comparison', 'comparison']);
  assert.deepEqual(missing, []);
  assert.equal(candidates.length, raw.length);
  const odd = policy.orderCandidates([...raw, { policy: 'future_x', damage: 1 }]);
  assert.equal(odd.candidates.at(-1).info.role, 'unknown');
  assert.deepEqual(policy.orderCandidates(raw.slice(0, 3)).missing, ['client_f32']);
});

await check('policy_select_unchanged_until_wire_confirmed', () => {
  assert.equal(policy.CLIENT_F32_WIRE.confirmed, false);
  const live = policy.policyOptions();
  assert.deepEqual(live.map(o => o.value), ['legacy_term_floor', 'final_round_even', 'nested_floor']);
  assert.equal(live.find(o => o.selected).value, 'legacy_term_floor');
  assert.equal(policy.defaultPolicy(), 'legacy_term_floor');
  const b = policy.policyOptions(true);
  assert.deepEqual(b.map(o => o.value), ['client_f32', 'legacy_term_floor', 'final_round_even', 'nested_floor']);
  assert.equal(b.find(o => o.selected).value, 'client_f32');
  assert.ok(b.slice(1).every(o => o.label.startsWith('비교 후보 · ')));
});

await check('experimental_inputs_neutral_and_strict', () => {
  assert.deepEqual(policy.EXPERIMENTAL_HIT_INPUTS.map(s => [s.key, s.neutral]), [['statDamageRatio', 1], ['defenceRatioRate', 0]]);
  assert.ok(policy.EXPERIMENTAL_HIT_INPUTS.every(s => s.note.includes('실험·미확정')));
  assert.equal(policy.parseExperimentalInput('statDamageRatio', '2'), 2);
  assert.equal(policy.parseExperimentalInput('defenceRatioRate', '.25'), 0.25);
  for (const bad of ['', ' ', 'abc', '1,5', 'Infinity']) assert.throws(() => policy.parseExperimentalInput('statDamageRatio', bad));
  assert.throws(() => policy.parseExperimentalInput('defenceRatioRate', '1.01'));
  assert.throws(() => policy.parseExperimentalInput('statDamageRatio', '-0.1'));
});

await check('wire_long_number_or_string', () => {
  assert.deepEqual(policy.readWireLong(4460740), { value: 4460740, text: '4460740', exact: true });
  assert.equal(policy.readWireLong('9007199254740993').exact, false);
  assert.equal(policy.readWireLong('9007199254740993').text, '9007199254740993');
  assert.equal(policy.readWireLong('12').exact, true);
  assert.equal(policy.readWireLong(1.5), null);
  assert.equal(policy.readWireLong('1e3'), null);
});

await check('client_breakdown_reads_recorded_terms', () => {
  const b = adapter.buildDamageBreakdown(entryFor('crit_core_fullburst_distance'));
  assert.equal(b.policy, 'client_f32');
  assert.deepEqual(b.missing, []);
  const terms = Object.fromEntries(mock.cases.crit_core_fullburst_distance.comparison.candidates.at(-1).terms.map(t => [t.name, t.after]));
  assert.equal(b.client.attack.value, terms.effectiveAttack);
  assert.equal(b.client.difference.value, terms.difference);
  assert.equal(b.client.bonus, terms.B);
  assert.equal(b.client.product, terms.product);
  assert.equal(b.client.final.value, 4460740);
  assert.equal(b.finalMatchesStored, true);
  assert.equal(b.attackDefenseDifference, terms.difference);
  assert.equal(b.client.statDamageRatio, 1);
  assert.equal(b.client.defenceRatioRate, 0);
  assert.equal(b.client.minimumApplied, false);
  assert.ok(b.steps.every(s => !s.label.startsWith('기록 항목')), 'every client term has a label');
  assert.equal(b.steps.find(s => s.name === 'base').label.startsWith('base = 공방차'), true);
});

await check('client_panel_formula_and_experimental_labels', () => {
  const html = panel(entryFor('crit_core_fullburst_distance'));
  const t = text(html);
  assert.ok(!t.includes('B3 × B4 × B5'), 'earlier B3~B5 card must not appear for client_f32');
  for (const needle of ['statDamageRatio', '1 − defenceRatioRate', '실험·미확정', 'extra', '잠정 대응', '사사오입', 'client_f32', '4,460,740', '저장된 발당 피해와 일치'])
    assert.ok(t.includes(needle), needle);
  const formula = adapter.describeRoundingFormula('client_f32');
  assert.ok(formula.some(l => l.includes('crit') || l.includes('크리 → 코어 → 풀버스트 → 적정 거리')));
  assert.ok(formula.some(l => l.includes('0.5는 0에서 먼 쪽')));
  assert.ok(formula.some(l => l.includes('long 정수')));
});

await check('client_variants_ratio_inputs_shown', () => {
  const quarter = panel(entryFor('crit_core_fullburst_distance__defence_ratio_quarter'));
  assert.ok(text(quarter).includes('입력 0.25'));
  assert.ok(text(quarter).includes('0.75'));
  const two = adapter.buildDamageBreakdown(entryFor('crit_core_fullburst_distance__stat_damage_ratio_two'));
  assert.equal(two.client.statDamageRatio, 2);
  assert.notEqual(two.client.final.value, 4460740);
});

await check('client_missing_ratio_is_unrecorded_not_neutral', () => {
  const entry = entryFor('crit_core_fullburst_distance');
  const hit = { ...entry.hit }; delete hit.statDamageRatio; delete hit.defenceRatioRate;
  const b = adapter.buildDamageBreakdown({ ...entry, hit });
  assert.equal(b.client.statDamageRatio, null);
  assert.equal(b.client.defenceRatioRate, null);
  assert.ok(text(panel({ ...entry, hit })).includes('미기록'));
  const noTerms = adapter.buildDamageBreakdown({ ...entry, calculation: { ...entry.calculation, terms: entry.calculation.terms.filter(t => t.name !== 'B') } });
  assert.deepEqual(noTerms.missing, ['B']);
});

await check('client_minimum_via_max1', () => {
  const b = adapter.buildDamageBreakdown(entryFor('minimum_damage'));
  assert.equal(b.client.final.value, 1);
  assert.equal(b.client.minimumApplied, true);
  assert.ok(text(panel(entryFor('minimum_damage'))).includes('최소 피해 1 적용'));
});

await check('client_large_long_string_not_rounded_silently', () => {
  const entry = entryFor('crit_core_fullburst_distance');
  const terms = entry.calculation.terms.map(t => t.name === 'final' ? { ...t, after: '9007199254740993' } : t);
  const t = text(panel({ ...entry, damage: null, calculation: { ...entry.calculation, terms } }));
  assert.ok(t.includes('9007199254740993 (JSON 정밀도 초과)'));
});

await check('effect_axes_named_by_client_term', () => {
  const entry = entryFor('crit_core_fullburst_distance', 'client_f32', {
    buffs: [
      { effect: { source: '5008', target: 'boss', functionId: 127031004, type: 42, value: 0.3926, stacks: 1, basis: 'native_caster', expiresAt: null }, appliedAtFrame: 0 },
      { effect: { source: '5011', target: '5004', functionId: 108231001, type: 51, value: 0.1249, stacks: 1, basis: 'native_recipient', expiresAt: null }, appliedAtFrame: 0 }
    ] });
  const audit = adapter.buildHitAudit(entry, null);
  const axes = audit.effects.applied.map(e => e.axis);
  assert.ok(axes.includes('damageReductionRate · 받는 대미지'), axes.join(','));
  assert.ok(axes.includes('B · criticalDamageRate'), axes.join(','));
  const legacy = adapter.buildHitAudit({ ...entry, calculation: mock.cases.crit_core_fullburst_distance.comparison.candidates[0] }, null);
  assert.ok(legacy.effects.applied.map(e => e.axis).includes('B4 · 받는 대미지'));
});

await check('legacy_entries_render_as_before', () => {
  const t = text(panel(entryFor('crit_core_fullburst_distance', 'legacy_term_floor')));
  assert.ok(t.includes('B3 × B4 × B5'));
  assert.ok(!t.includes('비교 후보 정책'), 'comparison notice waits for stage B');
  assert.equal(adapter.buildDamageBreakdown(entryFor('crit_core_fullburst_distance', 'legacy_term_floor')).client, null);
});

const failed = checks.filter(c => !c.passed);
console.log(JSON.stringify({ evidence: 'mock_only_not_api', total: checks.length, failed: failed.length, checks }, null, 2));
if (failed.length) process.exit(1);
